// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onAnguloBaseChange();
void onAnguloCodoChange();
void onAnguloHombroChange();
void onAnguloMunecaRotChange();
void onAnguloMunecaVerChange();

int angulo_base;
int angulo_codo;
int angulo_hombro;
int angulo_muneca_rot;
int angulo_muneca_ver;

void initProperties(){

  ArduinoCloud.addProperty(angulo_base, READWRITE, ON_CHANGE, onAnguloBaseChange);
  ArduinoCloud.addProperty(angulo_codo, READWRITE, ON_CHANGE, onAnguloCodoChange);
  ArduinoCloud.addProperty(angulo_hombro, READWRITE, ON_CHANGE, onAnguloHombroChange);
  ArduinoCloud.addProperty(angulo_muneca_rot, READWRITE, ON_CHANGE, onAnguloMunecaRotChange);
  ArduinoCloud.addProperty(angulo_muneca_ver, READWRITE, ON_CHANGE, onAnguloMunecaVerChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
